# Generated by Django 2.2.6 on 2022-03-28 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Busqueda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('proyecto', models.CharField(max_length=100)),
                ('busqueda', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('evaluacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
