# Generated by Django 2.2.6 on 2022-03-29 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_busqueda_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busqueda',
            name='evaluacion',
        ),
        migrations.RemoveField(
            model_name='busqueda',
            name='url',
        ),
        migrations.CreateModel(
            name='ResultadoBusqueda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha modificacion')),
                ('url', models.CharField(max_length=100)),
                ('evaluacion', models.CharField(max_length=100)),
                ('busqueda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Busqueda')),
            ],
        ),
    ]
