# Generated by Django 2.2.6 on 2022-03-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20220329_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadobusqueda',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
