# Generated by Django 2.2.6 on 2022-04-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_auto_20220330_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='busqueda',
            name='tipobusqueda',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
