# Generated by Django 2.2.6 on 2022-04-19 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_busqueda_tipobusqueda'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadobusqueda',
            name='puntaje',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
