# Generated by Django 2.2.6 on 2022-04-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_resultadobusqueda_puntaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadobusqueda',
            name='posicion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultadobusqueda',
            name='puntaje',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
