# Generated by Django 2.2.6 on 2022-04-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0009_auto_20220420_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadobusqueda',
            name='idstring',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
