# Generated by Django 2.2.6 on 2022-04-21 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0010_resultadobusqueda_idstring'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadobusqueda',
            name='descripcion',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultadobusqueda',
            name='titulo',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
