# Generated by Django 2.2.6 on 2022-05-10 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0011_auto_20220421_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadobusqueda',
            name='descripcion',
            field=models.CharField(max_length=1500),
        ),
    ]
